# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  before_all do
    ENV['MATCH_KEYCHAIN_NAME'] = "AFJ-Mobile-Swift-CI"
    ENV['MATCH_KEYCHAIN_PASSWORD'] = ENV['MATCH_KEYCHAIN_NAME']
    cocoapods
  end

  desc "Sync certificates"
   lane :sync_certificates do

    create_keychain(
      name:ENV['MATCH_KEYCHAIN_NAME'],
      password:ENV['MATCH_KEYCHAIN_PASSWORD'],
      default_keychain:true,
      unlock:true,
      timeout:3600,
      add_to_search_list:true
      )

     match(
      type: "development",
      readonly: true,
      keychain_name:ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password:ENV['MATCH_KEYCHAIN_PASSWORD']
      )
   end

  lane :custom_lane do

    sync_certificates

    time = Time.new.strftime("%Y%m%d")  # 获取时间格式
    version = get_version_number#获取版本号
    ipaName = "Debug_#{version}_#{time}.ipa"        # eg: Debug_1.0_20200921

    asc_key_content = ENV['APP_STORE_CONNECT_API_KEY_CONTENT']
    asc_issuer_id = ENV['APP_STORE_CONNECT_ISSUER_ID']
    asc_key_id = ENV['APP_STORE_CONNECT_API_KEY_ID']

    #发布
    app_store_connect_api_key(
      key_id: asc_key_id,
      issuer_id: asc_issuer_id,
      key_content: asc_key_content,
      is_key_content_base64: true
    )

    # Creates a signed file
    gym(
      workspace:"AFJ-Mobile-Swift.xcworkspace",
      scheme:"AFJ-Mobile-Swift",
      output_name:"#{ipaName}",
      clean:true,
      configuration:"Debug",
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        method: "development",
        provisioningProfiles: {
          "com.alfred.AFJ-Mobile-Swift" => "match Development com.alfred.AFJ-Mobile-Swift",
        }
      },
      sdk: "iphoneos16.4",
      export_method:"development",
      output_directory:"./build/",
      include_symbols:true,
      include_bitcode:false,
      )
  end
end